Added How to make PR
WomenWhoCode/WWCode-London pull request #28
Opened 2022-10-08 07:13 UTC by yadavsairaj

Added contributing guide with git commands

## Type Of Change
- [ ] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

2022-10-08 07:36 UTC, yadavsairaj commented
Also while merging please add the **Hacktoberfest-accepted** label.
 Thank you

2022-10-10 17:36 UTC, yadavsairaj commented
Final 
![image](https://user-images.githubusercontent.com/67747523/194923304-1ca41582-35f8-40ea-b926-45224eed0ba3.png)

2022-10-12 21:35 UTC, bharitwal requested changes
@yadavsairaj Many Thanks for your contribution. 

LGTM.

Requested minor changes so that it's in sync with the remaining information in the guide.

2022-10-12 21:35 UTC, bharitwal commented on CONTRIBUTING.md
> +⚠️ **Make sure** not to commit `package.json` or `package-lock.json` file
This line can be removed

2022-10-12 21:35 UTC, bharitwal commented on CONTRIBUTING.md
> +git add public
`git add <file/folder>`

2022-10-12 21:35 UTC, bharitwal commented on CONTRIBUTING.md
> +git commit -m "<your_commit_message>"
I would suggest just using the command

`git commit`

This will allow the user to follow best practices for writing a git commit message. The `-m` option would make it difficult. Thoughts?

2022-10-12 21:35 UTC, bharitwal commented on CONTRIBUTING.md
> +## ⭐ HOW TO MAKE A PULL REQUEST:
Can you please capitalise the heading here?

2022-10-13 05:49 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## All the best! 🥇
done

2022-10-13 05:50 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## Style Guide for Git Commit Messages :memo:
done

2022-10-13 05:52 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## 💥 Issues
done

2022-10-13 05:54 UTC, yadavsairaj commented on CONTRIBUTING.md
> +---
done

2022-10-13 05:57 UTC, yadavsairaj commented on CONTRIBUTING.md
> +⚠️ **Make sure** not to commit `package.json` or `package-lock.json` file
done

2022-10-13 06:00 UTC, yadavsairaj commented on CONTRIBUTING.md
> +git add public
done

2022-10-13 06:08 UTC, yadavsairaj commented on CONTRIBUTING.md
> +git commit -m "<your_commit_message>"
It just autofill the Subject of Pull request tab. which we can change it though in github. 
Yeah but for making things easier we can go with just
 ``` bash
 git commit ```

2022-10-13 06:09 UTC, yadavsairaj commented on CONTRIBUTING.md
> +git commit -m "<your_commit_message>"
done

2022-10-13 06:18 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## ⭐ HOW TO MAKE A PULL REQUEST:
DONE

2022-10-13 07:03 UTC, bharitwal commented on CONTRIBUTING.md
> +## ⭐ HOW TO MAKE A PULL REQUEST:
I meant capitalizing to `How To Make A Pull Request` or `How to Make a Pull Request`

2022-10-13 07:53 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## ⭐ HOW TO MAKE A PULL REQUEST:
done

2022-10-13 07:54 UTC, yadavsairaj commented on CONTRIBUTING.md
> +## All the best! 🥇
done

2022-10-13 10:49 UTC, bharitwal approved these changes

2022-10-13 10:52 UTC, merged

2022-11-03 17:32 UTC, bharitwal commented
Fixes #19