Add README.md
WomenWhoCode/WWCode-London pull request #37
Opened 2022-10-27 19:49 UTC by jljohnson001

## Type Of Change
- [ ] Update documentation
- [ ] Add new event details
- [X] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Commit message is as per guidelines in the contributor guide

2022-10-27 22:31 UTC, irenkamalova requested changes

2022-10-27 22:31 UTC, irenkamalova commented on resources/frontend/README.md
> +
Let's use html tags to build a table:
< table >, < tbody >, < tr > , < td >

2022-10-27 22:31 UTC, irenkamalova commented on resources/frontend/README.md
> +- [Modern Front End Ecosystem: Overview & Trends](https://www.youtube.com/watch?v=9jV6URf0I84)
Let's build a table with more description: 

- event link: https://www.meetup.com/women-who-code-london/events/288908790/
- the whole description 
- a few words about author

Follow example here: https://github.com/WomenWhoCode/WWCode-London/blob/main/README.md#event-resources

You can copy the image from meetUp and add it to images to create a separate column with posters

2022-10-27 22:43 UTC, irenkamalova commented on resources/frontend/README.md
> +|                                                                                                        | Description                 |
Tool

2022-10-29 14:29 UTC, bharitwal commented on resources/frontend/README.md
> +|                                                                                                        | Description                 |
+1

2022-10-30 08:28 UTC, bharitwal commented on resources/frontend/README.md
> +<td style="1px solid black" align="left" width="20%"><img alt="Modern Front End Ecosystem" align="left" src="resources/frontend/images/ivan-kolotilov.png"/>&nbsp;</td>
Image is not rendering correctly. 

Please check the path.

2022-10-30 08:40 UTC, jljohnson001 commented on resources/frontend/README.md
> +<td style="1px solid black" align="left" width="20%"><img alt="Modern Front End Ecosystem" align="left" src="resources/frontend/images/ivan-kolotilov.png"/>&nbsp;</td>
The pathing here is correct, but it only seemed to be resolved when updating from absolute to relative

2022-10-30 10:07 UTC, bharitwal approved these changes
LGTM.

Thanks for your contribution.

2022-10-30 19:03 UTC, irenkamalova approved these changes

2022-10-30 19:03 UTC, irenkamalova commented
Great job! 👏

2022-10-30 19:18 UTC, jljohnson001 commented
FYI @irenkamalova and @bharitwal, looks like you will have to merge the PR as I do not have write access.

2022-10-30 20:58 UTC, bharitwal commented
> FYI @irenkamalova and @bharitwal, looks like you will have to merge the PR as I do not have write access.

Yes , sure. I was waiting for Irena to confirm if she is happy with the changes.

2022-10-30 20:59 UTC, merged

2022-10-30 21:02 UTC, bharitwal commented
fixes #36