Bookclub branch
WomenWhoCode/WWCode-London pull request #38
Opened 2022-10-27 21:10 UTC by j4sum

## Type Of Change
- [ ] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

2022-10-27 21:14 UTC, j4sum commented
Once approved, I will update where required

2022-10-29 14:26 UTC, bharitwal requested changes
LGTM. 

Requested some minor changes.

2022-10-29 14:26 UTC, bharitwal commented on resources/book-club/README.md
> + [Blogpost](https://iren-kamalova.medium.com/grit-factor-cc597dbf107f)
This is not embedding the url correctly.

You can see it here : https://github.com/j4sum/WWCode-London/tree/bookclub-branch/resources/book-club

2022-10-29 14:26 UTC, bharitwal commented on resources/book-club/README.md
> +<tr>
Blog Post can be added : https://www.womenwhocode.com/blog/quiet-book-club-wwcode-london

2022-10-29 14:26 UTC, bharitwal commented on resources/book-club/README.md
> +- LinkedIn - https://www.linkedin.com/company/wwcodelondon/events/
```suggestion
- [LinkedIn](https://www.linkedin.com/company/wwcodelondon/events/)
```

2022-10-29 14:26 UTC, bharitwal commented on resources/book-club/README.md
> +- Meetup - https://meetu.ps/c/1Cj0v/yRb71/d
```suggestion
- [Meetup](https://meetu.ps/c/1Cj0v/yRb71/d)
```

2022-10-29 14:26 UTC, bharitwal commented on resources/book-club/README.md
> +- Meetup - https://meetu.ps/c/1Cj0v/yRb71/d
Would be nice to add all our social media handles.

You can refer to the information here: https://github.com/WomenWhoCode/WWCode-London#social

2022-10-30 21:04 UTC, bharitwal commented
fixes #27

2022-11-10 17:04 UTC, bharitwal commented
Hey @j4sum - Since this PR has been open for a while it is out of sync with with the fork. Please can you sync the changes in your fork.

2022-11-16 21:51 UTC, closed without merging