doc: Mock-Interviews: Algorithms & Data Structure
WomenWhoCode/WWCode-London pull request #41
Opened 2022-11-08 23:49 UTC by dricazenck

## Type Of Change
- [x] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

2022-11-08 23:51 UTC, dricazenck commented on resources/mock-interviews/README.md
> +You have to [complete the form](TODO_GET_LINK) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
TODO: to be fixed with the final link from the event and the form.

2022-11-09 09:12 UTC, dricazenck commented on README.md
> +- [Materials](resources/mock-interviews/mock-code-interview)
@irenkamalova do we have the presentation from Anna to share also?

2022-11-09 14:09 UTC, IdayatSanni reviewed
I reviewed the commits

2022-11-09 17:50 UTC, IdayatSanni reviewed
Changed some information

2022-11-09 17:50 UTC, IdayatSanni commented on resources/mock-interviews/mock-code-interview/README.md
> +Mock Interviews are very helpful in the way to preparing for real interviews! Women Who Code London help participant of the community to organise mock interviews and practise tackling interview with
```suggestion
Mock Interviews are very helpful in preparing for real interviews! Women Who Code London help participant of the community to organise mock interviews and practise tackling interview with each other!
```

2022-11-09 17:50 UTC, IdayatSanni commented on resources/mock-interviews/README.md
> +  - Agree the date-time and preferred meeting tool (zoom, google meet, webex, MS teams, etc) with the candidate
```suggestion
  - Agree on the date-time and preferred meeting tool (zoom, google meet, webex, MS teams, etc) with the candidate
```

2022-11-09 17:50 UTC, IdayatSanni commented on resources/mock-interviews/README.md
> +Mock Interviews are very helpful in the way to preparing for real interviews! Women Who Code London help participant of the community to organise mock interviews and practise tackling interview with
```suggestion
Mock Interviews are very helpful in preparing for real interviews! Women Who Code London helps participants of the community to organise mock interviews and practise tackling interviews with each other!
```

2022-11-09 21:19 UTC, irenkamalova commented on README.md
> +- [Materials](resources/mock-interviews/mock-code-interview)
Yes! Please, find it here:
https://docs.google.com/presentation/d/1-FiCp8KOQCjUmwz05JADm8umNU3TljRTPyAzs70bGJI/

2022-11-09 21:22 UTC, irenkamalova commented
Great job! 👏 
I like that you also added links to external video-resources! 👍
Let me know when you need an approve?
The form will be ready today!

2022-11-09 22:39 UTC, irenkamalova commented on resources/mock-interviews/README.md
> +You have to [complete the form](TODO_GET_LINK) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
https://forms.gle/7Rp6E1Ncj6gzS1fH6

2022-11-10 17:19 UTC, bharitwal commented on resources/mock-interviews/mock-code-interview/README.md
> +- Check the workshop [Mock-Interviews: Algorithms & Data Structure](https://www.youtube.com/watch?v=nWHQ0g8sorI).
This is pointing to the behavioural interview youtube video rather than the algorithms one. 

Needs to be updated.

2022-11-10 17:25 UTC, bharitwal commented on resources/mock-interviews/mock-code-interview/README.md
> +- [Mock Technical Interview (Coding/Algorithms in JavaScript)](https://youtu.be/yju4zwKSriI?t=474)
@sapphireduffy  Can you please suggest if its ok to to add these external links to Women Who Code Resources as a recommended tool to prepare for technical coding interviews. I didn't feel very comfortable with it, hence double checking with you.

2022-11-10 17:30 UTC, bharitwal commented on README.md
> +Mock Interviews are very helpful in the way to preparing for real interviews! Women Who Code London help participant of the community to organise mock interviews and practise tackling interview with
Might be worth updating this to the same description as in resources/mock-interviews/README.md

```suggestion
Mock Interviews are very helpful in preparing for real interviews! Women Who Code London helps participants of the community to organise mock interviews and practise tackling interviews with each other!
```

2022-11-10 17:42 UTC, bharitwal commented on resources/mock-interviews/README.md
> +- You will receive an email with a contact of the person your matched with or information that we couldn’t find a match for you.
Would be useful to add the timeline for this stage so that members are aware.

2022-11-10 17:46 UTC, bharitwal commented on resources/mock-interviews/README.md
> +You have to [complete the form](https://forms.gle/7Rp6E1Ncj6gzS1fH6) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
Is there a better way to manage the form and event link ?

- The event link will be outdated and someone will have to keep updating it in the repo requiring additional manual overhead.
- The form should be ok. But I see the form has specific dates. Not sure if we can update the date in the same form for future events and will it impact the data for the person performing the matching process. 

I mean can we add it as a bookmark to the slack channel. Specially the event link will be outdated and someone will have to keep updating in the repo. The form should e

2022-11-10 17:50 UTC, bharitwal commented on resources/mock-interviews/README.md
> +
Would be helpful to have a consistent terminology here as its a bit confusing. Currently there are 3 terms:

- Primary and Secondary
- Opponent
- Candidate

If we can just use 1 terminology that would be really helpful. Probably primary - secondary.

2022-11-10 18:52 UTC, bharitwal requested changes
Thank you for your contribution @dricazenck .

LGTM. Have left few comments for minor changes.

Will wait for Sapphire to confirm regarding external youtube videos.

2022-11-11 10:35 UTC, dricazenck commented on resources/mock-interviews/README.md
> +You have to [complete the form](https://forms.gle/7Rp6E1Ncj6gzS1fH6) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
@bharitwal I understand your concerns, and they make sense. But this material will be used for the mock interview week event (which will be to promote this week first, as it was in the last event). 
I will be responsible to update the document before the event and after, so I will make sure to have everything up-to-date. 

Based on the discussed I had with @irenkamalova before.

2022-11-11 10:41 UTC, dricazenck commented on resources/mock-interviews/mock-code-interview/README.md
> +- [Mock Technical Interview (Coding/Algorithms in JavaScript)](https://youtu.be/yju4zwKSriI?t=474)
@bharitwal It is not about promoting external resources, but about recommending an extra resource to support our community to prepare for the mock interview. Currently, a lot of girls struggle and think they are not prepared, so giving extra material can give them the confidence they need to join the week and have a better engagement. 

But since I am not sure about any "rule" from the global team, it is nice you mentioned it.

2022-11-11 10:43 UTC, dricazenck commented on resources/mock-interviews/mock-code-interview/README.md
> +- Check the workshop [Mock-Interviews: Algorithms & Data Structure](https://www.youtube.com/watch?v=nWHQ0g8sorI).
Nice catch, thanks.

2022-11-11 11:54 UTC, irenkamalova commented on resources/mock-interviews/README.md
> +You have to [complete the form](https://forms.gle/7Rp6E1Ncj6gzS1fH6) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
Good point!
@dricazenck, let's add a form and link to the event to the mock-interview channel!
That will allow us to manage cycles in the channel and reduce the need to update this documentation indeed. 🚀 

Nice catch! Thank you @bharitwal!

2022-11-11 11:55 UTC, irenkamalova commented on resources/mock-interviews/README.md
> +  - Once a request has been accepted by the interviewer, the candidate should agree the date-time and the preferred meeting tool (zoom, google meet, webex, MS teams, etc) for the mock behvaioural int
mock behvaioural interview -> mock interviews

2022-11-11 14:34 UTC, dricazenck commented on resources/mock-interviews/README.md
> +You have to [complete the form](https://forms.gle/7Rp6E1Ncj6gzS1fH6) before the deadline mentioned in [event](TODO_GET_EVENT_LINK)
Done.

2022-11-11 18:47 UTC, irenkamalova reviewed
It's a fantastic job!

2022-11-12 12:10 UTC, sapphireduffy commented on resources/mock-interviews/mock-code-interview/README.md
> +- [Mock Technical Interview (Coding/Algorithms in JavaScript)](https://youtu.be/yju4zwKSriI?t=474)
@bharitwal this looks great! It is fine to link Women Who Code Resources here.

2022-11-13 13:57 UTC, bharitwal approved these changes

2022-11-13 13:59 UTC, merged

2022-11-15 11:33 UTC, bharitwal commented
fixes #26