Update Resources
WomenWhoCode/WWCode-London pull request #42
Opened 2022-11-09 18:24 UTC by mariastoo

1. Edit Educational Programmes' table. 
2. Create additional folders in Resources.
3. Add tables with events videos & speakers to the folders in Resources.

## Type Of Change
- [ ] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

2022-11-09 21:57 UTC, irenkamalova reviewed
Great job!👍
I left two comments.
Please let me know when it's ready! 👌

2022-11-09 21:57 UTC, irenkamalova commented on resources/backend/README.md
> +  [Tech Talks: Triangle of Cassandra & Solr & Kafka](https://www.youtube.com/watch?v=zJNe3Gp1Qmg&list=PLVcEZG2JPVhcxbBrvAfF0I4YSme5sCYcL&index=7)</th>
You can move here:
[Tech Talks: Writing Code is Easy, Being a Great Developer is Hard](https://www.youtube.com/watch?v=TNfklR1NAqY&list=PLVcEZG2JPVhcxbBrvAfF0I4YSme5sCYcL&index=28)

2022-11-09 21:57 UTC, irenkamalova commented on resources/data-analytics/README.md
> +  [Helen Tabunshchyk](https://www.linkedin.com/in/helentb/)</td>
It's Galyna Tabunshchyk :) 
I found a link to her profile: https://www.linkedin.com/in/galyna-tabunshchyk-53005959/

2022-11-10 16:51 UTC, mariastoo commented on resources/backend/README.md
> +  [Tech Talks: Triangle of Cassandra & Solr & Kafka](https://www.youtube.com/watch?v=zJNe3Gp1Qmg&list=PLVcEZG2JPVhcxbBrvAfF0I4YSme5sCYcL&index=7)</th>
Done!

2022-11-10 18:02 UTC, bharitwal commented on README.md
> +  <td>[Data Structures 101](https://www.youtube.com/watch?v=6XVZvDy49bE&list=PLVcEZG2JPVhdzf4cgDxH2TK4U1uEfaF8E&index=1)</td>
Some of the urls in this table haven't rendered correctly.

Please double check. You can refer here : https://github.com/mariastoo/WWCode-London_mariastoo/tree/mariastoo_branch#readme

2022-11-10 18:13 UTC, bharitwal commented on resources/soft-skills/README.md
> +Placeholder for the soft-skills special interest group
It seems like these can all be moved under the 'general' directory.

The differentiation between the 2 is not very clear. IMHO, to keep it simple for future contributors it would be helpful to just have 1 directory not related to a technical track or any of our programs. 

@irenkamalova  - thoughts? Like the book club event should be under general rather than soft-skills. If we have 2 directories, it will cause confusion. Hence best to have it in 1 location.

2022-11-10 18:46 UTC, bharitwal commented on resources/mock-interviews/mock-behavioral-interview/README.md
> +## Events
These events should be added to a readme under mock-interviews at the parent level. 

For reference, there is another PR #41 raised which adds resources for the technical mock-interviews.

2022-11-10 19:30 UTC, bharitwal requested changes
Thank you for contribution @mariastoo .

LGTM. Added comments for few minor changes. 

Also, aesthetically it would be nice to align the session name to the right in all the tables. Currently its in the centre.

2022-11-11 11:34 UTC, irenkamalova commented on resources/mock-interviews/mock-behavioral-interview/README.md
> +## Events
Good point!

The right place is a `resources/mock-interviews/README.md`

@mariastoo you can wait for PR #41 or you can merge this PR without changes on those events and create one PR when file `resources/mock-interviews/README.md` will be in master.

What do you prefer?

2022-11-11 11:39 UTC, irenkamalova commented on resources/soft-skills/README.md
> +Placeholder for the soft-skills special interest group
I want it to be in separate directory but 'career-progression' instead of 'soft-skills'.
We have a few blogposts dedicated to career progression and as the next step for this folder, we can those blogposts!

2022-11-11 21:33 UTC, mariastoo commented on resources/mock-interviews/mock-behavioral-interview/README.md
> +## Events
I'd prefer waiting for PR #41 then

2022-11-15 11:36 UTC, bharitwal commented on resources/mock-interviews/mock-behavioral-interview/README.md
> +## Events
Just a heads up that PR #41 was merged.

2022-11-15 18:52 UTC, mariastoo commented on resources/mock-interviews/mock-behavioral-interview/README.md
> +## Events
Thanks! I've updated my PR. Can you please check again?

2022-11-15 20:33 UTC, irenkamalova reviewed
Small remark about line
https://github.com/WomenWhoCode/WWCode-London/blob/e7d6756c6de1d4afd6e0fe68615954b60c286704/README.md?plain=1#L12

Everything else is good!

2022-11-15 20:33 UTC, irenkamalova commented on README.md
> +  <th>programme</th> <th>session</th> <th>speaker(s)</th>
```suggestion
  <th>Programme</th> <th>Session</th> <th>Speaker(s)</th>
```

2022-11-15 21:59 UTC, bharitwal approved these changes
Thank you very much for taking the time to add these resources.

2022-11-15 22:01 UTC, merged

2022-11-15 22:02 UTC, bharitwal commented
fixes #45