Update Links in README
WomenWhoCode/WWCode-London pull request #5
Opened 2022-09-11 21:39 UTC by dricazenck

Just minor adjustments in the README file. 

* Correct event link 
* Markdown cleanup 
* Add the slack channel link

## Type Of Change
- [x] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

2022-09-12 09:37 UTC, bharitwal requested changes
LGTM. Thanks for your contribution.

Added a few comments before I could merge the changes.

2022-09-12 09:37 UTC, bharitwal commented on CONTRIBUTING.md
> +    h) Update the SLACK_CHANNEL_ID from Slack worspace
Small typo - 'workspace' spelling 
```suggestion
    h) Update the SLACK_CHANNEL_ID from Slack workspace
```

2022-09-12 09:37 UTC, bharitwal commented on README.md
> +
This section should not be added to this readme:

- It should have its own directory under the resources folder with its own readme providing details about how to be involved. Similar to the readme under the Mock Interviews project. All projects supported by WWC-London would end up in the resources folder. Maybe I should rename 'resources' to  'projects'. Thoughts? 
- The link that is added here does not give details about the WWC-London mentorship program - dates, how to participate,  etc. These are just general guidelines for mentors and mentees.

2022-09-13 15:56 UTC, dricazenck commented
Sorry I will create another pr, because I cannot update this one anymore.

2022-09-13 15:56 UTC, closed without merging